spring:
  datasource:
    url: jdbc:mysql://192.168.18.100:3306/lyflexi?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml